### PR TITLE
Wire up EnvResolver in node-cli, pass through to root via Opts struct

### PR DESCRIPTION
**Pull request by justnoise**
This is a small change that allows us to keep using node-cli while passing objects and arguments through to the root command by putting those things in the `Opts` struct.

I realize `Opts` was only holding command line flags but I thought this was better than creating an additional `Config` structure that also gets passed through to the root command.

This will go alongside changes that are going into virtual-kubelet.  I think we can move kip over to our own version of node-cli.  I will hold off on using this fork in kip until the env var change lands in virtual-kubelet.

### CODE REVIEW

**Comment by ldx** [comment]
Do you plan on fixing all virtual-kubelet/node-cli package imports?

**Comment by justnoise** [comment]
Yes, I need to fix those.  I'll push a change. I had been using this in my own branch by using the `source` directive in Gopkg.toml

**Review by ldx — APPROVED** [review]
:+1:

**Comment by ldx** [comment]
@justnoise is this ready to go?

**Comment by justnoise** [comment]
This is currently on hold since it won't work with the current version of virtual-kubelet. We would need to push the env changes through to make them work together.

**Comment by justnoise** [comment]
Closing this one...

**Pull request closed without merging**
